/** ISO 3166-1 alpha-2 → 日本語国名マップ（主要国） */
export const COUNTRY_NAMES: Record<string, string> = {
  JP: "日本",
  US: "アメリカ",
  CN: "中国",
  KR: "韓国",
  TW: "台湾",
  HK: "香港",
  SG: "シンガポール",
  TH: "タイ",
  VN: "ベトナム",
  PH: "フィリピン",
  ID: "インドネシア",
  MY: "マレーシア",
  IN: "インド",
  AU: "オーストラリア",
  NZ: "ニュージーランド",
  GB: "イギリス",
  DE: "ドイツ",
  FR: "フランス",
  IT: "イタリア",
  ES: "スペイン",
  NL: "オランダ",
  BE: "ベルギー",
  CH: "スイス",
  AT: "オーストリア",
  SE: "スウェーデン",
  NO: "ノルウェー",
  DK: "デンマーク",
  FI: "フィンランド",
  PT: "ポルトガル",
  IE: "アイルランド",
  PL: "ポーランド",
  CZ: "チェコ",
  RU: "ロシア",
  UA: "ウクライナ",
  CA: "カナダ",
  MX: "メキシコ",
  BR: "ブラジル",
  AR: "アルゼンチン",
  CL: "チリ",
  CO: "コロンビア",
  PE: "ペルー",
  ZA: "南アフリカ",
  EG: "エジプト",
  NG: "ナイジェリア",
  KE: "ケニア",
  AE: "アラブ首長国連邦",
  SA: "サウジアラビア",
  IL: "イスラエル",
  TR: "トルコ",
  PK: "パキスタン",
  BD: "バングラデシュ",
  MM: "ミャンマー",
  KH: "カンボジア",
  LA: "ラオス",
  NP: "ネパール",
  LK: "スリランカ",
  MN: "モンゴル",
};

/** 国コードから日本語名を取得（不明な場合はコードをそのまま返す） */
export function getCountryName(code: string | null | undefined): string {
  if (!code) return "不明";
  return COUNTRY_NAMES[code.toUpperCase()] ?? code;
}
